# Define a versão do Docker Compose. '3.8' é uma versão moderna e recomendada.
version: '3.8'

# A seção 'services' é onde definimos os contêineres que compõem nossa aplicação.
services:
  # 'api' é o nome que damos ao nosso serviço/contêiner da aplicação Python.
  api:
    # 'build: .' instrui o Docker Compose a construir uma imagem a partir do Dockerfile no diretório atual.
    build: . 
    # 'ports' mapeia portas entre a máquina host e o contêiner (HOST:CONTAINER).
    container_name: api # Define o nome do contêiner.
    ports:
      - "8000:8000" # Expõe a porta 8000 do contêiner na porta 8000 da sua máquina.
    # 'volumes' sincroniza arquivos/pastas entre a máquina host e o contêiner (HOST:CONTAINER).
    volumes:
      - .:/app # Mapeia o diretório atual do projeto para o diretório /app dentro do contêiner, permitindo o live-reload.
    # 'command' sobrescreve o comando padrão (CMD) do Dockerfile.
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload # Executa o servidor com recarregamento automático.

